AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS ETL Pipeline - S3 ➜ Lambda ➜ Cleaned CSV ➜ S3

Resources:

  SourceS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-source-bucket"

  DestinationS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-destination-bucket"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: 
                  - !Sub "arn:aws:s3:::${AWS::StackName}-source-bucket/*"
                  - !Sub "arn:aws:s3:::${AWS::StackName}-destination-bucket/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-etl-function"
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: your-lambda-code-bucket-name
        S3Key: lambda-function-code.zip
      Timeout: 300
      MemorySize: 512
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          DEST_BUCKET: !Ref DestinationS3Bucket

  LambdaS3TriggerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt SourceS3Bucket.Arn

  LambdaTrigger:
    Type: AWS::S3::BucketNotification
    Properties:
      Bucket: !Ref SourceS3Bucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LambdaFunction.Arn

Outputs:

  SourceBucketName:
    Description: Source S3 bucket name
    Value: !Ref SourceS3Bucket

  DestinationBucketName:
    Description: Destination S3 bucket name
    Value: !Ref DestinationS3Bucket

  LambdaFunctionName:
    Description: Name of the deployed Lambda function
    Value: !Ref LambdaFunction
